rebuild trac package and job using bosh-gen

diff --git a/packages/trac/packaging b/packages/trac/packaging
--- a/packages/trac/packaging
+++ b/packages/trac/packaging
@@ -1,8 +1,17 @@
-# abort script on any command that exits with a non zero value
-set -e
+set -e # exit immediately if a simple command exits with a non-zero status
+set -u # report the usage of uninitialized variables
+
+# Available variables
+# $BOSH_COMPILE_TARGET - where this package & spec'd source files are available
+# $BOSH_INSTALL_TARGET - where you copy/install files to be included in package
+export HOME=/var/vcap
+export TRAC_HOME=$HOME/trac
+
+echo "Creating $TRAC_HOME..."
+mkdir -p $TRAC_HOME
 
 curl https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py > ez_setup.py
-python ez_setup.py 
+python ez_setup.py
 
 echo "Extracting trac..."
 tar xzf trac/Trac-1.0.1.tar.gz
@@ -10,13 +19,14 @@ tar xzf trac/Trac-1.0.1.tar.gz
 echo "Copying trac to bosh install target..."
 cp -r Trac-1.0.1 ${BOSH_INSTALL_TARGET}
 
-cd ${BOSH_INSTALL_TARGET}/Trac-1.0.1
+cd Trac-1.0.1
 
 echo "Installing trac..."
 python setup.py install
 
 echo "Creating trac project..."
-trac-admin /usr/local/mytracproject initenv "My Project" sqlite:db/myproject.db
+trac-admin $TRAC_HOME/mytracproject initenv "My Project" sqlite:db/myproject.db
 
 echo "Giving permissions to /usr/local/mytracproject/conf/trac.ini"
-chmod a+r /usr/local/mytracproject/conf/trac.ini
+chmod a+r $TRAC_HOME/mytracproject/conf/trac.ini
+
